### ISSUE TITLE
small objects

### ISSUE THREAD

**Issue by fatandfat** [mnslarcher/kmeans-anchors-ratios#11]
hi @mnslarcher ,I'm training with zylo's efficientdet d2, my dataset's images are of height * weight of 64 * 1024, my objects are all like 10 * 40 of h * w, so how should I set my anchor scales and anchor ratios? I'm so confused by the input size and images size things, thanks for your repo and hopes you can help me with it😭

**Comment by mnslarcher** [comment]
> hi @mnslarcher ,I'm training with zylo's efficientdet d2, my dataset's images are of height * weight of 64 * 1024, my objects are all like 10 * 40 of h * w, so how should I set my anchor scales and anchor ratios? I'm so confused by the input size and images size things, thanks for your repo and hopes you can help me with it😭

Hi @fatandfat , if you select EfficientDet2 (default input size = 768) the Zylo's repo (like many others) will:
* Resize images so that the largest side is 768 (from 64 * 1024 to 48 * 768, 48 is 64 * (768 / 1024 ))
* Pad your images with zeros until it became square (768 * 768)

If you are ok with this, is very easy to use this repo, just set `PHI = 2` in the [tutorial](https://github.com/mnslarcher/kmeans-anchors-ratios/blob/master/tutorial.ipynb) (and replace 
`INSTANCES_PATH = "./annotations/instances_train2017.json"` with your annotations) to get your optimal anchors ratios.

You probably notice that with the default approach:
* Your images after pre-processing will be mostly black (for the padding)
* You are losing some resolution

Given that your images are far from square I would also consider to preprocess them dividing the images in 4 parts of 64 * 256 pixels and then create new images putting one part in top of the other. In this way you will get square images 256 * 256 and your model will see everything with full resolution, even if you use EfficientDet0 that by default have an input size of 512 (you can also lower the default input resolution at this point to 256 and see if it works better or worsts).

If you decide to try this more "complex" approach you will need also to adapt your annotations. Is nothing particularly difficult but it requires some preparatory work, if is your first time that you do something like this I suggest you to start from the default approach.

**Comment by fatandfat** [comment]
> > hi @mnslarcher ,I'm training with zylo's efficientdet d2, my dataset's images are of height * weight of 64 * 1024, my objects are all like 10 * 40 of h * w, so how should I set my anchor scales and anchor ratios? I'm so confused by the input size and images size things, thanks for your repo and hopes you can help me with it😭
> 
> Hi @fatandfat , if you select EfficientDet2 (default input size = 768) the Zylo's repo (like many others) will:
> * Resize images so that the largest side is 768 (from 64 * 1024 to 48 * 768, 48 is 64 * (768 / 1024 ))
> * Pad your images with zeros until it became square (768 * 768)
> 
> If you are ok with this, is very easy to use this repo, just set `PHI = 2` in the [tutorial](https://github.com/mnslarcher/kmeans-anchors-ratios/blob/master/tutorial.ipynb) (and replace 
> `INSTANCES_PATH = "./annotations/instances_train2017.json"` with your annotations) to get your optimal anchors ratios.
> 
> You probably notice that with the default approach:
> * Your images after pre-processing will be mostly black (for the padding)
> * You are losing some resolution
> 
> Given that your images are far from square I would also consider to preprocess them dividing the images in 4 parts of 64 * 256 pixels and then create new images putting one part in top of the other. In this way you will get square images 256 * 256 and your model will see everything with full resolution, even if you use EfficientDet0 that by default have an input size of 512 (you can also lower the default input resolution at this point to 256 and see if it works better or worsts).
> 
> If you decide to try this more "complex" approach you will need also to adapt your annotations. Is nothing particularly difficult but it requires some preparatory work, if is your first time that you do something like this I suggest you to start from the default approach.

Thanks for your help, I think I'm now clear with it!
