### ISSUE TITLE
K-Means anchors ratios calculator.: error: the following arguments are required: --instances, --input-size

### ISSUE THREAD

**Issue by Ronald-Kray** [mnslarcher/kmeans-anchors-ratios#13]
The error is still coming out.

<img width="1103" alt="Screenshot 2021-04-04 at 08 49 58" src="https://user-images.githubusercontent.com/76469976/113494392-c4e99080-9522-11eb-9051-42a4de734ff2.png">

**Comment by mnslarcher** [comment]
Hi @Ronald-Kray , you don't have to modify kmeans_anchors_ratios.py to run it with a different path, just run 

```bash
cd kmeans-anchors-ratios  # only if you aren't already in the folder
pip install -r requirements.txt  # you just need to do this the first time
python kmeans_anchors_ratios.py --instances {PUT_YOUR_PATH_HERE}
```
for example,

```bash
cd kmeans-anchors-ratios
pip install -r requirements.txt
python kmeans_anchors_ratios.py --instances .\\annotations\\my_file.json
```

Or use the notebook that maybe is easier.

**Comment by Ronald-Kray** [comment]
@mnslarcher 
Thanks.
Can I calculate anchors scale on my dataset for EfficientDet?

**Comment by Ronald-Kray** [comment]
@mnslarcher 
Thanks.
Can I calculate anchors scale on my dataset for EfficietDet?

**Comment by mnslarcher** [comment]
Hi @Ronald-Kray , this repo finds automatically the optimal ratios but you can try to manually change the scales and compare the results, I suggest you to do it interactively in the notebook where you can also inspect what kind of bounding boxes your combination of ratios and scales is missing. Then you need to check in the repo that you are using and see how you need to change these hyper parameters in that implementation of EfficientDet (there are many).

**Comment by Ronald-Kray** [comment]
@mnslarcher 
Hi, Thanks for your work!.
I have a question about anchor size.
If I have 640 image size,  should I have set --anchors-sizes 32 64 128 256 512 640? (I mean including 640)
Thanks

**Comment by mnslarcher** [comment]
> 
> 
> @mnslarcher
> Hi, Thanks for your work!.
> I have a question about anchor size.
> If I have 640 image size, should I have set --anchors-sizes 32 64 128 256 512 640? (I mean including 640)
> Thanks

Hi @Ronald-Kray, you have to set the same values you are using in your model setup (check the code/doc of your model library if you don't know what the default values are or ask the author, in the notebook there is an example with EfficientDet), if you change something then you have to put the same values here to get the correct output (otherwise the outout % will be wrong). If your question is: in my model setup should I always use size = my image size? No, it's not necessary, in general you should choose dimensions in line (more or less) with the objects you want to identify. If most of your objects in your 640x640 images have a size around 128x128 you should set in your model at least one size not too distant from this value. Usually the default sizes are good and most of the time you probably want just to add a smaller size if your objects are very small (like 16)
